import { Scenario } from "./types";

export const scenarios: Scenario[] = [
  {
    id: "new-worker",
    title: "เพิ่งมาทำงานใหม่",
    titleEn: "New to Work",
    titleMm: "အလုပ်အသစ်",
    description: "ต้องการทราบสิทธิพื้นฐาน เอกสาร และการปรับตัว",
    descriptionEn: "Want to know basic rights, documents, and adaptation",
    descriptionMm:
      "အခြေခံအခွင့်အရေးများ၊ စာရွက်စာတမ်းများနှင့် လိုက်လျောညီထွေဖြစ်ရန်",
    icon: "/images/newjob-new.svg",
    iconType: "image",
    color: {
      bg: "bg-slate-50",
      border: "border-yellow-400",
      text: "text-slate-800",
      hoverBg: "hover:bg-slate-100",
    },
    keywords: ["เอกสาร", "ใบอนุญาต", "วีซ่า", "สิทธิพื้นฐาน"],
    keywordsEn: ["Documents", "Permit", "Visa", "Basic Rights"],
    keywordsMm: [
      "စာရွက်စာတမ်းများ",
      "ခွင့်ပြုမိန့်",
      "ဗီဇာ",
      "အခြေခံအခွင့်အရေးများ",
    ],
    category: "เอกสารและการเดินทาง",
    urgency: "high",
    priority: true,
  },
  {
    id: "workplace-problem",
    title: "มีปัญหาที่ทำงาน",
    titleEn: "Workplace Problems",
    titleMm: "အလုပ်ခွင်ပြဿနာများ",
    description: "ค่าแรงไม่ได้รับ ทำงานหนัก หรือถูกปฏิบัติไม่ดี",
    descriptionEn: "Unpaid wages, hard work, or mistreatment",
    descriptionMm:
      "လုပ်ခမရရှိခြင်း၊ လုပ်ငန်းခက်ခဲခြင်း သို့မဟုတ် အလွဲသုံးစားခံရခြင်း",
    icon: "/images/problem-job-new.svg",
    iconType: "image",
    color: {
      bg: "bg-slate-50",
      border: "border-yellow-400",
      text: "text-slate-800",
      hoverBg: "hover:bg-slate-100",
    },
    keywords: ["ค่าแรง", "ความปลอดภัย", "โอที", "การทำงาน"],
    keywordsEn: ["Wages", "Safety", "Overtime", "Work"],
    keywordsMm: ["လုပ်ခ", "ဘေးကင်းရေး", "အချိန်ပို", "အလုပ်"],
    category: "ทำงานและสวัสดิการ",
    urgency: "high",
    priority: true,
  },
  {
    id: "document-expiring",
    title: "เอกสารใกล้หมดอายุ",
    titleEn: "Documents Expiring",
    titleMm: "စာရွက်စာတမ်းများ သက်တမ်းကုန်ဆုံးမည်",
    description: "ต้องต่อใบอนุญาต วีซ่า หรือเอกสารสำคัญ",
    descriptionEn: "Need to renew permit, visa, or important documents",
    descriptionMm:
      "ခွင့်ပြုမိန့်၊ ဗီဇာ သို့မဟုတ် အရေးကြီးစာရွက်စာတမ်းများ သက်တမ်းတိုးရန်",
    icon: "/images/expire-workpermit-new.svg",
    iconType: "image",
    color: {
      bg: "bg-slate-50",
      border: "border-yellow-400",
      text: "text-slate-800",
      hoverBg: "hover:bg-slate-100",
    },
    keywords: ["ต่ออายุ", "ใบอนุญาต", "วีซ่า", "เอกสาร"],
    keywordsEn: ["Renewal", "Permit", "Visa", "Documents"],
    keywordsMm: [
      "သက်တမ်းတိုးခြင်း",
      "ခွင့်ပြုမိန့်",
      "ဗီဇာ",
      "စာရွက်စာတမ်းများ",
    ],
    category: "เอกสารและการเดินทาง",
    urgency: "medium",
    priority: true,
  },
  {
    id: "family-issues",
    title: "เรื่องครอบครัว",
    titleEn: "Family Matters",
    titleMm: "မိသားစုကိစ္စရပ်များ",
    description: "การแต่งงาน การมีบุตร การศึกษา หรือปัญหาครอบครัว",
    descriptionEn: "Marriage, children, education, or family issues",
    descriptionMm:
      "လက်ထပ်ခြင်း၊ သားသမီးများ၊ ပညာရေး သို့မဟုတ် မိသားစုပြဿနာများ",
    icon: "/images/family-new.svg",
    iconType: "image",
    color: {
      bg: "bg-slate-50",
      border: "border-yellow-400",
      text: "text-slate-800",
      hoverBg: "hover:bg-slate-100",
    },
    keywords: ["แต่งงาน", "บุตร", "การศึกษา", "ครอบครัว"],
    keywordsEn: ["Marriage", "Children", "Education", "Family"],
    keywordsMm: ["လက်ထပ်ခြင်း", "သားသမီးများ", "ပညာရေး", "မိသားစု"],
    category: "ครอบครัวและชีวิตในชุมชน",
    urgency: "medium",
    priority: true,
  },
  {
    id: "healthcare",
    title: "ปัญหาสุขภาพ",
    titleEn: "Health Issues",
    titleMm: "ကျန်းမာရေးပြဿနာများ",
    description: "ต้องการรักษา ประกันสุขภาพ หรือข้อมูลโรงพยาบาล",
    descriptionEn: "Need treatment, health insurance, or hospital information",
    descriptionMm: "ကုသမှု၊ ကျန်းမာရေးအာမခံ သို့မဟုတ် ဆေးရုံအချက်အလက်များ",
    icon: "/images/hospital-new.svg",
    iconType: "image",
    color: {
      bg: "bg-slate-50",
      border: "border-yellow-400",
      text: "text-slate-800",
      hoverBg: "hover:bg-slate-100",
    },
    keywords: ["รักษา", "ประกันสุขภาพ", "โรงพยาบาล", "สุขภาพ"],
    keywordsEn: ["Treatment", "Health Insurance", "Hospital", "Health"],
    keywordsMm: ["ကုသမှု", "ကျန်းမာရေးအာမခံ", "ဆေးရုံ", "ကျန်းမာရေး"],
    category: "ทำงานและสวัสดิการ",
    urgency: "high",
    priority: true,
  },
  {
    id: "community-life",
    title: "ชีวิตในชุมชน",
    titleEn: "Community Life",
    titleMm: "အသိုင်းအဝိုင်းဘဝ",
    description: "ปรับตัวเข้าสังคม ภาษา วัฒนธรรม และการอยู่ร่วมกัน",
    descriptionEn: "Social adaptation, language, culture, and living together",
    descriptionMm:
      "လူမှုရေးလိုက်လျောညီထွေဖြစ်ခြင်း၊ ဘာသာစကား၊ ယဉ်ကျေးမှုနှင့် အတူနေထိုင်ခြင်း",
    icon: "/images/community-new.svg",
    iconType: "image",
    color: {
      bg: "bg-slate-50",
      border: "border-yellow-400",
      text: "text-slate-800",
      hoverBg: "hover:bg-slate-100",
    },
    keywords: ["ภาษา", "วัฒนธรรม", "ชุมชน", "การปรับตัว"],
    keywordsEn: ["Language", "Culture", "Community", "Adaptation"],
    keywordsMm: [
      "ဘာသာစကား",
      "ယဉ်ကျေးမှု",
      "အသိုင်းအဝိုင်း",
      "လိုက်လျောညီထွေဖြစ်ခြင်း",
    ],
    category: "ครอบครัวและชีวิตในชุมชน",
    urgency: "low",
    priority: true,
  },
  {
    id: "emergency-help",
    title: "ฉุกเฉิน! ต้องการความช่วยเหลือ",
    titleEn: "Emergency! Need Help",
    titleMm: "အရေးပေါ်! အကူအညီလိုအပ်သည်",
    description: "สถานการณ์ฉุกเฉิน ถูกคุกคาม หรือต้องการช่วยเหลือทันที",
    descriptionEn: "Emergency situation, threatened, or need immediate help",
    descriptionMm:
      "အရေးပေါ်အခြေအနေ၊ ခြိမ်းခြောက်ခံရခြင်း သို့မဟုတ် ချက်ချင်းအကူအညီလိုအပ်ခြင်း",
    icon: "/images/help-new.svg",
    iconType: "image",
    color: {
      bg: "bg-red-50",
      border: "border-red-200",
      text: "text-red-800",
      hoverBg: "hover:bg-red-100",
    },
    keywords: ["ฉุกเฉิน", "ช่วยเหลือ", "สายด่วน", "ตำรวจ"],
    keywordsEn: ["Emergency", "Help", "Hotline", "Police"],
    keywordsMm: ["အရေးပေါ်", "အကူအညီ", "အရေးပေါ်ဖုန်း", "ရဲ"],
    category: "emergency",
    urgency: "high",
    priority: true,
  },
  {
    id: "legal-rights",
    title: "ต้องการรู้สิทธิ",
    titleEn: "Know Your Rights",
    titleMm: "သင့်အခွင့်အရေးများကို သိပါ",
    description: "ศึกษาสิทธิตามกฎหมาย และวิธีการคุ้มครองตนเอง",
    descriptionEn: "Learn about legal rights and self-protection methods",
    descriptionMm:
      "ဥပဒေအရအခွင့်အရေးများနှင့် မိမိကိုယ်ကို ကာကွယ်သောနည်းလမ်းများ",
    icon: "/images/know-your-right-new.svg",
    iconType: "image",
    color: {
      bg: "bg-slate-50",
      border: "border-yellow-400",
      text: "text-slate-800",
      hoverBg: "hover:bg-slate-100",
    },
    keywords: ["กฎหมาย", "สิทธิ", "คุ้มครอง", "ความรู้"],
    keywordsEn: ["Law", "Rights", "Protection", "Knowledge"],
    keywordsMm: ["ဥပဒေ", "အခွင့်အရေးများ", "ကာကွယ်မှု", "အသိပညာ"],
    category: "general",
    urgency: "low",
    priority: true,
  },
];
